apiVersion: v1
kind: Service
metadata:
  name: meteorologia-mock-api-service
  labels:
    app: meteorologia-mock-api
    app.kubernetes.io/name: meteorologia-mock-api
    app.kubernetes.io/component: microservice
  annotations:
    description: "Servicio para la API Mock de Meteorología"
spec:
  selector:
    app: meteorologia-mock-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: meteorologia-mock-api-route
  labels:
    app: meteorologia-mock-api
    app.kubernetes.io/name: meteorologia-mock-api
  annotations:
    description: "Ruta externa para la API Mock de Meteorología"
    haproxy.router.openshift.io/timeout: "60s"
spec:
  to:
    kind: Service
    name: meteorologia-mock-api-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None